# Generated by Django 4.1.3 on 2022-11-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64, unique=True)),
                ('num', models.IntegerField()),
                ('file_url', models.CharField(max_length=255)),
            ],
        ),
    ]
